name = "example"
uuid = "5908719f-22a4-4d2a-944a-f70cf8660f1f"
authors = ["Katherine Rosenfeld <56368533+krosenfeld-IDM@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
